name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test-postgres:
    strategy:
      fail-fast: false
      matrix:
        redmica_version: ["v2.3.0", "master"]
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        options: --shm-size=256m
        ports:
          - 4444:4444
      db:
        image: postgres:11
        env:
          LANG: C.UTF-8
          POSTGRES_INITDB_ARGS: --locale=C.UTF-8
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          chmod +x /__w/redmica_ui_extension/redmica_ui_extension/.github/scripts/setup-redmica.sh
          /__w/redmica_ui_extension/redmica_ui_extension/.github/scripts/setup-redmica.sh ${{matrix.redmica_version}} postgres /usr/src/redmine
      - name: Test RedMica UI Extension plugin
        run: cd /usr/src/redmine; RAILS_ENV=test bundle exec rake test TEST=plugins/redmica_ui_extension/test
      - name: Store screenshots Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-postgres-screenshots
      - name: Test RedMica
        run: cd /usr/src/redmine; RAILS_ENV=test bundle exec rake test

  test-mysql:
    strategy:
      fail-fast: false
      matrix:
        redmica_version: [master, v2.2.1]
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7
    services:
      chrome:
        image: seleniarm/standalone-chromium:latest
        options: --shm-size=256m
        ports:
          - 4444:4444
      db:
        image: mysql:5
        env:
          MYSQL_ROOT_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          chmod +x /__w/redmica_ui_extension/redmica_ui_extension/.github/scripts/setup-redmica.sh
          /__w/redmica_ui_extension/redmica_ui_extension/.github/scripts/setup-redmica.sh ${{matrix.redmica_version}} mysql /usr/src/redmine
      - name: Test RedMica UI Extension plugin
        run: cd /usr/src/redmine; RAILS_ENV=test bundle exec rake test TEST=plugins/redmica_ui_extension/test
      - name: Store screenshots Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-mysql-screenshots
          path: /usr/src/redmine/tmp/screenshots
      - name: Test RedMica
        run: cd /usr/src/redmine; RAILS_ENV=test bundle exec rake test

  test-sqlite:
    strategy:
      fail-fast: false
      matrix:
        redmica_version: [master, v2.2.1]
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7
    services:
      chrome:
        image: seleniarm/standalone-chromium:latest
        options: --shm-size=256m
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          chmod +x /__w/redmica_ui_extension/redmica_ui_extension/.github/scripts/setup-redmica.sh
          /__w/redmica_ui_extension/redmica_ui_extension/.github/scripts/setup-redmica.sh ${{matrix.redmica_version}} sqlite /usr/src/redmine
      - name: Test RedMica UI Extension plugin
        run: cd /usr/src/redmine; RAILS_ENV=test bundle exec rake test TEST=plugins/redmica_ui_extension/test
      - name: Store screenshots Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-sqlite-screenshots
      - name: Test RedMica
        run: cd /usr/src/redmine; RAILS_ENV=test bundle exec rake test
